server:
  port: 6010
  servlet:
    context-path: /selling/
spring:
  application:
    name: eureka-server
eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:6010/selling/eureka/