apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-clients-manager-secrets
  labels:
    namespace: auth
    app: auth-clients-manager
data:
  POSTGRES_PASSWORD: '123'
  POSTGRES_USER: 'admin'
  POSTGRES_DB: 'users-db'
  POSTGRES_URL: 'r2dbc:postgresql://postgres-service:5432/'
  ENABLE_LOGGING_FILES: 'false'
  PORT: '7043'
