apiVersion: v1
kind: Service
metadata:
  name: auth-clients-manager-service
  labels:
    namespace: auth
    app: auth-clients-manager
spec:
  type: ClusterIP
  ports:
    - port: 7043
  selector:
    namespace: auth
    app: auth-clients-manager