spring:
  webflux:
    base-path: /selling/query/save/sale/v1/
  data:
    mongodb:
      uri: mongodb://localhost:27017/sample_supplies
  application:
    name: sales-save-ms
server:
  port: 6019
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/selling/query/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    groups:
      enabled: true
    path: /api/docs