server:
  port: 7031
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
config:
  services:
    context-path:
      data-manager-ms: "http://DATA-MANAGER-MS/selling/data/manager/sale/v1/"

