spring:
  webflux:
    base-path: /selling/auth/manager/v1/
  application:
    name: auth-clients-manager
server:
  port: 7043
  servlet:
    context-path: /selling/auth/clients/manager/v1/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6010/selling/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    groups:
      enabled: true
    path: /api/docs

