package com.selling.system.auth.shared.module.models.enums;

public enum Query {
    RETRIEVE_ALL_PROFILES,
    RETRIEVE_PROFILE,
    RETRIEVE_PROFILE_AUTHORITIES_KEYS,
    IS_PROFILE_NAME_EXISTS,
    ADD_PROFILE_AUTHORITIES,
    ADD_PROFILE,
    DELETE_PROFILE,
    DELETE_ALL_PROFILE_AUTHORITIES,
    DELETE_PROFILE_AUTHORITIES,
}
