package com.selling.system.auth.shared.module.models.enums;

public enum Query {
    RETRIEVE_ALL_PROFILES,
    RETRIEVE_ALL_AUTHORITIES,
    RETRIEVE_PROFILE,
    RETRIEVE_PROFILE_AUTHORITIES_KEYS,
    RETRIEVE_AUTHORITIES_KEYS,
    RETRIEVE_ALL_GROUPS,
    IS_PROFILE_NAME_EXISTS,
    ADD_PROFILE_AUTHORITIES,
    ADD_PROFILE,
    ADD_AUTHORITY,
    ADD_GROUP,
    DELETE_PROFILE,
    DELETE_ALL_PROFILE_AUTHORITIES,
    DELETE_PROFILE_AUTHORITIES,
    UPDATE_PROFILE_NAME,
    UPDATE_GROUP_NAME,
    UPDATE_AUTHORITY_NAME,
    AUTHORITY_VALUES
}
