version: '3.9'
name: selling-export-category
services:
  export-data-manager:
    build:
      context: ./export-data-manager
    image: export/export-data-manager
    ports:
      - "7035:7035"
    networks:
      - network
      - selling-shared-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
      WEB_CLIENT_BUFFER_SIZE: 16MB
    depends_on:
      - export-data-xml
      - export-data-pdf
      - export-data-json
      - export-data-xlsx
      - export-data-csv
    command: java -jar export-data-manager-1.0.0-SNAPSHOT.jar --spring.config.location=classpath:/application.yaml,classpath:/application-prod.yaml

  export-data-csv:
    build:
      context: ./export-data-csv
    image: export/export-data-csv
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
    command: java -jar export-data-csv-1.0.0-SNAPSHOT.jar --spring.config.location=classpath:/application.yaml,classpath:/application-prod.yaml


  export-data-xlsx:
    build:
      context: ./export-data-xlsx
    image: export/export-data-xlsx
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
    command: java -jar export-data-xlsx-1.0.0-SNAPSHOT.jar --spring.config.location=classpath:/application.yaml,classpath:/application-prod.yaml

  export-data-json:
    build:
      context: ./export-data-json
    image: export/export-data-json
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
    command: java -jar export-data-json-1.0.0-SNAPSHOT.jar --spring.config.location=classpath:/application.yaml,classpath:/application-prod.yaml

  export-data-pdf:
    build:
      context: ./export-data-pdf
    image: export/export-data-pdf
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
    command: java -jar export-data-pdf-1.0.0-SNAPSHOT.jar --spring.config.location=classpath:/application.yaml,classpath:/application-prod.yaml

  export-data-xml:
    build:
      context: ./export-data-xml
    image: export/export-data-xml
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
    command: java -jar export-data-xml-1.0.0-SNAPSHOT.jar --spring.config.location=classpath:/application.yaml,classpath:/application-prod.yaml


networks:
  network:
    name: selling-export-network
  selling-shared-network:
    external: true
  selling-data-network:
    external: true