version: '3.9'
name: selling-export-category
services:
  export-data-manager:
    build:
      context: ./export-data-manager
    image: export/export-data-manager:1.0.0
    ports:
      - "7035:7035"
    networks:
      - network
      - selling-shared-network
    depends_on:
      - export-data-xml
      - export-data-pdf
      - export-data-json
      - export-data-xlsx
      - export-data-csv
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
      WEB_CLIENT_BUFFER_SIZE: 16MB
      ENABLE_LOGGING_FILES: false
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/export/export-data-manager:/app/logs

  export-data-csv:
    build:
      context: ./export-data-csv
    image: export/export-data-csv:1.0.0
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
      ENABLE_LOGGING_FILES: false
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/export/export-data-csv:/app/logs

  export-data-xlsx:
    build:
      context: ./export-data-xlsx
    image: export/export-data-xlsx:1.0.0
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
      ENABLE_LOGGING_FILES: false
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/export/export-data-xlsx:/app/logs

  export-data-json:
    build:
      context: ./export-data-json
    image: export/export-data-json:1.0.0
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
      ENABLE_LOGGING_FILES: false
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/export/export-data-json:/app/logs

  export-data-pdf:
    build:
      context: ./export-data-pdf
    image: export/export-data-pdf:1.0.0
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
      ENABLE_LOGGING_FILES: false
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/export/export-data-pdf:/app/logs

  export-data-xml:
    build:
      context: ./export-data-xml
    image: export/export-data-xml:1.0.0
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
      ENABLE_LOGGING_FILES: false
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/export/export-data-xml:/app/logs

networks:
  network:
    name: selling-export-network
  selling-shared-network:
    external: true
  selling-data-network:
    external: true