server:
  port: 6041
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
config:
  services:
    context-path:
      data-manager-ms: "http://DATA-MANAGER/selling/data/manager/sale/v1/"


