spring:
  webflux:
    base-path: /selling/modify/sales/save/v1/
  application:
    name: modify-save-sales-ms
server:
  port: 7021
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/selling/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    groups:
      enabled: true
    path: /api/docs
config:
  services:
    context-path:
      kafka-sale-producer-ms: http://KAFKA-SALE-PRODUCER-MS/selling/kafka/sale/v1/