server:
  port: 6015
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    template:
      default-topic: persistence.sale.json
      partitions: 3
      replicas: 1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  webflux:
    base-path: /selling/persistence/sale/v1/