server:
  port: 7042
config:
  logging:
    enable: ${ENABLE_LOGGING_FILES}
spring:
  r2dbc:
    url: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    name: ${POSTGRES_DB}