spring:
  application:
    name: receipt-generator-ms
  webflux:
    base-path: /selling/reports/generate/sale/v1/
server:
  port: 6013
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/selling/eureka/