server:
  port: 6061
emit:
  duration: ${EMIT_DURATION}
  max:
    items: ${NUMBER_ITEMS}
    tags: ${NUMBER_TAGS}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
config:
  services:
    context-path:
      kafka-sale-producer-ms: "http://KAFKA-SALE-PRODUCER-MS/selling/kafka/sale/v1/"