server:
  port: ${PORT}
config:
  services:
    context-path:
      export-data-csv: ${EXPORT_DATA_CSV_URL}
      export-data-xlsx: ${EXPORT_DATA_XLSX_URL}
      export-data-json: ${EXPORT_DATA_JSON_URL}
      export-data-xml: ${EXPORT_DATA_XML_URL}
      export-data-pdf: ${EXPORT_DATA_PDF_URL}
  web-client:
    buffer: ${WEB_CLIENT_BUFFER_SIZE}
  logging:
    enable: ${ENABLE_LOGGING_FILES}