apiVersion: v1
kind: Service
metadata:
  name: export-data-xlsx
  labels:
    namespace: export
    app: export-data-xlsx
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    namespace: export
    app: export-data-xlsx