apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    namespace: auth
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql