apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    namespace: auth
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    namespace: auth
    app: postgres