spring:
  application:
    name: calc-price-ms
  webflux:
    base-path: /selling/reports/calc/price/v1/
server:
  port: 6021
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/selling/eureka/