spring:
  webflux:
    base-path: /selling/export/sales/xml/v1/
  application:
    name: export-data-xml
server:
  port: 7034
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6010/selling/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    groups:
      enabled: true
    path: /api/docs
config:
  services:
    context-path:
      data-manager-ms: "http://DATA-MANAGER-MS/selling/data/manager/sale/v1/"

