server:
  port: 8001
  servlet:
    context-path: /selling/reports/
spring:
  application:
    name: reports-eureka-server
eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8001/selling/reports/eureka/