apiVersion: v1
kind: ConfigMap
metadata:
  name: export-data-pdf
  labels:
    namespace: export
    app: export-data-pdf
data:
  application.properties: |-
    server.port=8080
    config.logging.enable=false
    config.services.context-path.data-manager-ms=http://data-manager.data.svc.cluster.local:8080/selling/data/manager/sale/v1/
