apiVersion: v1
kind: Service
metadata:
  name: auth-manager-service
  labels:
    namespace: auth
    app: auth-manager
spec:
  type: LoadBalancer
  ports:
    - port: 7040
  selector:
    namespace: auth
    app: auth-manager