server:
  port: 6040
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
  logging:
    enable: ${ENABLE_LOGGING_FILES}