spring:
  application:
    name: source-sales-pull
  webflux:
    base-path: /selling/source/pull/sale/v1/
server:
  port: 6060
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6010/selling/eureka/
emit:
  duration: 100
  max:
    items: 10
    tags: 3