server:
  port: 6060
emit:
  duration: ${EMIT_DURATION}
  max:
    items: ${NUMBER_ITEMS}
    tags: ${NUMBER_TAGS}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}