server:
  port: 6061
config:
  services:
    context-path:
      destination: ${DESTINATION_URL}
  emit:
    duration: ${EMIT_DURATION}
    max:
      items: ${NUMBER_ITEMS}
      tags: ${NUMBER_TAGS}
  logging:
    enable: ${ENABLE_LOGGING_FILES}