spring:
  webflux:
    base-path: /selling/auth/profiles/manager/v1/
  application:
    name: auth-profiles-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/users-db
    username: admin
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 7042
  servlet:
    context-path: /selling/auth/profiles/manager/v1/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6010/selling/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    groups:
      enabled: true
    path: /api/docs

