version: '3.9'
name: selling-kafka-sales-category
services:
  kafka-sale-consumer:
    build:
      context: ./kafka-sale-consumer
    image: kafka/sales/kafka-sale-consumer:1.0.0
    networks:
      - network
      - selling-shared-network
      - selling-kafka-network
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka1:19092
      
      ENABLE_LOGGING_FILES: false
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/kafka/sales/kafka-sale-consumer:/app/logs

  kafka-sale-producer:
    build:
      context: ./kafka-sale-producer
    image: kafka/sales/kafka-sale-producer:1.0.0
    networks:
      - network
      - selling-kafka-network
      - selling-shared-network
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka1:19092
      
      ENABLE_LOGGING_FILES: false
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/kafka/sales/kafka-sale-producer:/app/logs

networks:
  network:
    name: selling-kafka-sales-network
  selling-shared-network:
    external: true
  selling-kafka-network:
    external: true