spring:
  webflux:
    base-path: /selling/auth/clients/manager/v1/
  application:
    name: auth-clients-manager
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/users-db
    username: admin
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:vault://
server:
  port: 7043
  servlet:
    context-path: /selling/auth/clients/manager/v1/
springdoc:
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-basic-authentication-with-access-code-grant: true
  api-docs:
    groups:
      enabled: true
    path: /api/docs

