server:
  port: 7043
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
config:
  logging:
    enable: ${ENABLE_LOGGING_FILES}
spring:
  r2dbc:
    url: ${DATABASE_URL}
  cloud:
    vault:
      host: ${VAULT_HOSTNAME}
      port: ${VAULT_PORT}