spring:
  webflux:
    base-path: /selling/export/sales/json/v1/
  application:
    name: export-data-json
server:
  port: 7033

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    groups:
      enabled: true
    path: /api/docs
config:
  services:
    context-path:
      data-manager-ms: "http://DATA-MANAGER/selling/data/manager/sale/v1/"

