apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      namespace: redis
      app: redis
  template:
    metadata:
      labels:
        namespace: redis
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: Always
          command: ["redis-server"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /conf
              name: conf
      volumes:
        - name: conf
          configMap:
            name: redis-cluster-configmap
