apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: export
  name: export-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: export
  name: export-service-account
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "pods", "services", "endpoints", "secrets" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: export
  name: export-service-account
subjects:
  - kind: ServiceAccount
    namespace: export
    name: export-service-account
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: export-service-account
