apiVersion: v1
kind: Service
metadata:
  name: auth-profiles-manager-service
  labels:
    namespace: auth
    app: auth-profiles-manager
spec:
  type: ClusterIP
  ports:
    - port: 7042
  selector:
    namespace: auth
    app: auth-profiles-manager