spring:
  application:
    name: reports-calc-price
  webflux:
    base-path: /selling/reports/calc/price/v1/
server:
  port: 6021
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6010/selling/eureka/