spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/sample_supplies
  webflux:
    base-path: /selling/fetch/stores/v1/
  application:
    name: fetch-stores-ms
server:
  port: 6012
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/selling/eureka/