server:
  port: 7030
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6010/selling/eureka/
config:
  services:
    context-path:
      data-manager-ms: "http://DATA-MANAGER-MS/selling/data/manager/sale/v1/"

