version: '3.9'
name: 'selling-shared-category'
services:
  eureka-server:
    ports:
      - "6010:6010"
    build:
      context: ./eureka-server
    image: shared/eureka-server:1.0.0
    environment:
      ENABLE_LOGGING_FILES: false
    networks:
      - network
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/shared/eureka-server:/app/logs

  selling-system-database:
    image: mongo
    container_name: selling-system-database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
    networks:
      - network
    volumes:
      - mongodb_data:/data/db

  users-system-database:
    image: postgres:16-alpine
    container_name: users-system-database
    ports:
      - "5432:5432"
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=users-db
    networks:
      - network

  vault:
    build:
      context: .
      dockerfile: ./vault/Dockerfile
    image: shared/vault:1.0.0
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file

volumes:
  mongodb_data:
  postgresdb_data:
  vault_data:
networks:
  network:
    name: selling-shared-network