version: '3.9'
name: selling-reports-category
services:
  reports-receipt-generator:
    build:
      context: ./reports-receipt-generator
    image: reports/reports-receipt-generator:1.0.0
    ports:
      - "6020:6020"
    networks:
      - network
      - selling-shared-network
      - selling-data-network
    depends_on:
      - reports-calc-price
    environment:
      
      ENABLE_LOGGING_FILES: false
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/report/reports-receipt-generator:/app/logs

  reports-calc-price:
    build:
      context: ./reports-calc-price
    image: reports/reports-calc-price:1.0.0
    networks:
      - network
      - selling-shared-network
    environment:
      
      ENABLE_LOGGING_FILES: false
    volumes:
      - /Users/abdfrehat/Frehat/Code/Projects/Selling-System/logs/report/reports-calc-price:/app/logs

networks:
  network:
    name: selling-reports-network
  selling-shared-network:
    external: true
  selling-data-network:
    external: true