server:
  port: 7020
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
config:
  services:
    context-path:
      modify-delete-sales-ms: "http://MODIFY-DELETE-SALES-MS/selling/modify/sales/delete/v1/"
      modify-save-sales-ms: "http://MODIFY-SAVE-SALES-MS/selling/modify/sales/save/v1/"
      modify-update-sales-ms: "http://MODIFY-UPDATE-SALES-MS/selling/modify/sales/update/v1/"