spring:
  webflux:
    base-path: /selling/modify/router/manager/sales/v1/
  application:
    name: modify-router-sales-manager
server:
  port: 7020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/selling/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    groups:
      enabled: true
    path: /api/docs