spring:
  webflux:
    base-path: /selling/auth/manager/v1/
  application:
    name: auth-manager
  data:
    redis:
      port: 6379
      host: localhost
  cloud:
    vault:
      host: localhost
      port: 8200
      token: hvs.fR2VweCctXKiMheXN4fzCHvx
      scheme: http
      kv:
        backend: kv
        default-context: auth-manager
  config:
    import: optional:vault://
server:
  port: 7040
  servlet:
    context-path: /selling/auth/manager/v1/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6010/selling/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    groups:
      enabled: true
    path: /api/docs
config:
  services:
    context-path:
      paths:
        auth-clients-manager: "http://AUTH-CLIENTS-MANAGER/selling/auth/clients/manager/v1/"
        auth-users-manager: "http://AUTH-USERS-MANAGER/selling/auth/users/manager/v1/"
  auth:
    access-token:
      expiration-time: 3600
    refresh-token:
      expiration-time: 2592000
    auth-code:
      length: 64
      expiration-time: 10

