server:
  port: ${PORT}
config:
  logging:
    enable: ${ENABLE_LOGGING_FILES}
  services:
    context-path:
      paths:
        auth-clients-manager: ${auth-clients-manager-url}
        auth-users-manager: ${auth-users-manager-url}
  auth:
    key: ${AUTH_KEY}
logging:
  level:
    root: ${LOG_LEVEL}
spring:
  data:
    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES}