server:
  port: ${PORT}
config:
  logging:
    enable: ${ENABLE_LOGGING_FILES}
  services:
    context-path:
      paths:
        auth-clients-manager: ${auth-clients-manager-url}
        auth-users-manager: ${auth-users-manager-url}
  auth:
    key: ${AUTH_KEY}