server:
  port: 7040
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
config:
  logging:
    enable: ${ENABLE_LOGGING_FILES}
spring:
  cloud:
    vault:
      host: ${VAULT_HOSTNAME}
      port: ${VAULT_PORT}