spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/sample_supplies
  webflux:
    base-path: /selling/fetch/sale/items/v1/
  application:
    name: fetch-items-ms
server:
  port: 6011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/selling/fetch/eureka/