server:
  port: 8000
spring:
  application:
    name: fetch-eureka-server
eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka/
