version: '3.9'
name: selling-modify-category
services:
  modify-router-sales-manager:
    build:
      context: ./modify-sales-manager
    image: modify/modify-router-sales-manager
    ports:
      - "7020:7020"
    networks:
      - network
      - selling-shared-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
    depends_on:
      - modify-delete-sales
      - modify-save-sales
      - modify-update-sales
    command: java -jar modify-sales-manager-1.0.0-SNAPSHOT.jar --spring.config.location=classpath:/application.yaml,classpath:/application-prod.yaml

  modify-delete-sales:
    build:
      context: ./modify-delete-sales
    image: modify/modify-delete-sales
    networks:
      - network
      - selling-shared-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
    command: java -jar modify-delete-sales-1.0.0-SNAPSHOT.jar --spring.config.location=classpath:/application.yaml,classpath:/application-prod.yaml


  modify-update-sales:
    build:
      context: ./modify-update-sales
    image: modify/modify-update-sales
    networks:
      - network
      - selling-shared-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
    command: java -jar modify-update-sales-1.0.0-SNAPSHOT.jar --spring.config.location=classpath:/application.yaml,classpath:/application-prod.yaml

  modify-save-sales:
    build:
      context: ./modify-save-sales
    image: modify/modify-save-sales
    networks:
      - network
      - selling-shared-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-server:6010/selling/eureka/
    command: java -jar modify-save-sales-1.0.0-SNAPSHOT.jar --spring.config.location=classpath:/application.yaml,classpath:/application-prod.yaml

networks:
  network:
    name: selling-modify-network
  selling-shared-network:
    external: true