apiVersion: v1
kind: Service
metadata:
  name: auth-users-manager-service
  labels:
    namespace: auth
    app: auth-users-manager
spec:
  type: ClusterIP
  ports:
    - port: 7041
  selector:
    namespace: auth
    app: auth-users-manager